// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TunifyPlatform.Data;

#nullable disable

namespace TunifyPlatform.Migrations
{
    [DbContext(typeof(TunifyDbContext))]
    [Migration("20240819081122_AddSeedingData")]
    partial class AddSeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TunifyPlatform.Models.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Album_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Artist_ID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Release_Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("album");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album_Name = "Album 1",
                            Artist_ID = 1,
                            Release_Date = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Album_Name = "Album 2",
                            Artist_ID = 2,
                            Release_Date = new DateTime(2021, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Album_Name = "Album 3",
                            Artist_ID = 3,
                            Release_Date = new DateTime(2022, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("artist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bio = "Bio for Artist 1",
                            Name = "Artist 1"
                        },
                        new
                        {
                            Id = 2,
                            Bio = "Bio for Artist 2",
                            Name = "Artist 2"
                        },
                        new
                        {
                            Id = 3,
                            Bio = "Bio for Artist 3",
                            Name = "Artist 3"
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.Playlist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created_Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlayList_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("User_ID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("playlist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(4019),
                            PlayList_Name = "Playlist 1",
                            User_ID = 1
                        },
                        new
                        {
                            Id = 2,
                            Created_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(4021),
                            PlayList_Name = "Playlist 2",
                            User_ID = 2
                        },
                        new
                        {
                            Id = 3,
                            Created_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(4022),
                            PlayList_Name = "Playlist 3",
                            User_ID = 3
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.PlaylistSongs", b =>
                {
                    b.Property<int>("Playlist_ID")
                        .HasColumnType("int");

                    b.Property<int>("Song_ID")
                        .HasColumnType("int");

                    b.HasKey("Playlist_ID", "Song_ID");

                    b.HasIndex("Song_ID");

                    b.ToTable("playlistSongs");

                    b.HasData(
                        new
                        {
                            Playlist_ID = 1,
                            Song_ID = 1
                        },
                        new
                        {
                            Playlist_ID = 2,
                            Song_ID = 2
                        },
                        new
                        {
                            Playlist_ID = 3,
                            Song_ID = 3
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Album_ID")
                        .HasColumnType("int");

                    b.Property<int>("Artist_ID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Artist_ID");

                    b.ToTable("song");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Album_ID = 1,
                            Artist_ID = 1,
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            Genre = "Pop",
                            Title = "Song 1"
                        },
                        new
                        {
                            Id = 2,
                            Album_ID = 2,
                            Artist_ID = 2,
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            Genre = "Rock",
                            Title = "Song 2"
                        },
                        new
                        {
                            Id = 3,
                            Album_ID = 3,
                            Artist_ID = 3,
                            Duration = new TimeSpan(0, 0, 3, 45, 0),
                            Genre = "Jazz",
                            Title = "Song 3"
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("price")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("supscribtion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Free",
                            price = "0"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Premium",
                            price = "9.99m"
                        },
                        new
                        {
                            Id = 3,
                            Type = "Family",
                            price = "14.99m"
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Join_Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Subscription_ID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("user");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "user1@example.com",
                            Join_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(3934),
                            Subscription_ID = 1,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "user2@example.com",
                            Join_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(3951),
                            Subscription_ID = 2,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = 3,
                            Email = "user3@example.com",
                            Join_Date = new DateTime(2024, 8, 19, 11, 11, 22, 593, DateTimeKind.Local).AddTicks(3952),
                            Subscription_ID = 3,
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("TunifyPlatform.Models.PlaylistSongs", b =>
                {
                    b.HasOne("TunifyPlatform.Models.Playlist", "Playlist")
                        .WithMany("playlistSongs")
                        .HasForeignKey("Playlist_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TunifyPlatform.Models.Song", "Song")
                        .WithMany("playlistSongs")
                        .HasForeignKey("Song_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("TunifyPlatform.Models.Song", b =>
                {
                    b.HasOne("TunifyPlatform.Models.Artist", "artist")
                        .WithMany("song")
                        .HasForeignKey("Artist_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("artist");
                });

            modelBuilder.Entity("TunifyPlatform.Models.Artist", b =>
                {
                    b.Navigation("song");
                });

            modelBuilder.Entity("TunifyPlatform.Models.Playlist", b =>
                {
                    b.Navigation("playlistSongs");
                });

            modelBuilder.Entity("TunifyPlatform.Models.Song", b =>
                {
                    b.Navigation("playlistSongs");
                });
#pragma warning restore 612, 618
        }
    }
}
